### ISSUE TITLE
Listened tracks history is not saved on Last.fm

### ISSUE THREAD

**Issue by Granga** [mopidy/mopidy-scrobbler#10]
Last.fm shows only the currently playing song.
When song finishes, it isn't saved in last.fm history.
This happens in both cases:
   - played > 30s
   - played full song

My setup:
Mopidy 0.19.5
Mopidy-Scrobbler: 1.1.1
OS: Raspbian

**Comment by jodal** [comment]
Both "now playing" and "scrobbling" works for me with:

- Mopidy develop (0.20 to be, but shouldn't be any relevant changes here)
- Mopidy-Scrobbler 1.1.1
- pylast 0.5.11 from Ubuntu package python-pylast 0.5.11-1

I've noticed some activity in the pylast project recently, so I installed pylast 1.1.0 from PyPI, and retested. Both "now playing" and "scrobbling" still works.

Changed Mopidy version from the develop branch to the v0.19.5 tag, and everything still works.

How can I reproduce your issue?

**Comment by jodal** [comment]
BTW, the command `mopidy deps` will list which pylast version your installation of Mopidy-Scrobbler use.

**Comment by Granga** [comment]
My setup has pylast 1.1.0. Here's full dependencies output: https://gist.github.com/Granga/7d86d3bc765130d27f9a#file-gistfile1-txt

Normally, mopidy runs as service, but I also tried to run it manually. Still same issue.
Mopidy device is behind router, with UPnP disabled.

Just to make sure there's no problem with OS installation, soon I will try other OS and test from there.

**Comment by Granga** [comment]
I found what caused this problem:
The date/time of the machine was not up to date.

Updating the date/time fixed the issue.

Thanks.
