### ISSUE TITLE
Unhandled exception in ScrobblerFrontend

### ISSUE THREAD

**Issue by hlprimm** [mopidy/mopidy-scrobbler#15]
```
ERROR    Unhandled exception in ScrobblerFrontend (urn:uuid:CENSORED):
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 200, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 294, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib/python2.7/dist-packages/mopidy/core/listener.py", line 33, in on_event
    getattr(self, event)(**kwargs)
  File "/usr/share/mopidy/mopidy_scrobbler/frontend.py", line 50, in track_playback_started
    mbid=(track.musicbrainz_id or ''))
  File "/usr/lib/python2.7/dist-packages/pylast.py", line 465, in update_now_playing
    _Request(self, "track.updateNowPlaying", params).execute()
  File "/usr/lib/python2.7/dist-packages/pylast.py", line 828, in execute
    response = self._download_response()
  File "/usr/lib/python2.7/dist-packages/pylast.py", line 819, in _download_response
    self._check_response_for_errors(response_text)
  File "/usr/lib/python2.7/dist-packages/pylast.py", line 840, in _check_response_for_errors
    e = doc.getElementsByTagName('lfm')[0]
IndexError: list index out of range
```

Replaced my UUID with censored BTW. Not sure what is causing this

**Comment by jodal** [comment]
No need. The actor UUIDs are not useful outside that single process on your computer, and in this case, the actor in question just crashed with this exception. There'll probably never be anything else in the world using that exact UUID.

As for the exception, this looks like a crash down in pylast, either because of a bad assumption made by pylast or because last.fm returned a broken response. What version of pylast do you use? You can find the version in the output of the command `mopidy deps`.

**Comment by hlprimm** [comment]
Executable: /usr/bin/mopidy
Platform: Linux-3.16.0-38-generic-x86_64-with-Ubuntu-14.10-utopic
Python: CPython 2.7.8 from /usr/lib/python2.7
Mopidy: 1.0.5 from /usr/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
  tornado>=2.3: 3.2 from /usr/lib/python2.7/dist-packages
Mopidy-Spotify-Tunigo: 0.2.1 from /usr/share/mopidy
  Mopidy>=0.19.0: 1.0.5 from /usr/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
    tornado>=2.3: 3.2 from /usr/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
  mopidy-spotify>=1.2.0: 1.4.0 from /usr/share/mopidy
    Mopidy>=1.0: 1.0.5 from /usr/lib/python2.7/dist-packages
      Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
      tornado>=2.3: 3.2 from /usr/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
    pyspotify>=1.9,<1.999: 1.11 from /usr/lib/pymodules/python2.7
  tunigo: 0.1.3 from /usr/lib/python2.7/dist-packages
    requests>=2.0.0: 2.7.0 from /usr/local/lib/python2.7/dist-packages
Mopidy-GMusic: 0.3.0 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=0.18: 1.0.5 from /usr/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
    tornado>=2.3: 3.2 from /usr/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
  setuptools: 5.5.1 from /usr/lib/python2.7/dist-packages
  gmusicapi>=3.0.0: 6.0.0 from /usr/local/lib/python2.7/dist-packages
    decorator>=3.3.1: 3.4.2 from /usr/local/lib/python2.7/dist-packages
    oauth2client>=1.1: 1.4.11 from /usr/local/lib/python2.7/dist-packages
      httplib2>=0.9.1: 0.9.1 from /usr/local/lib/python2.7/dist-packages
      pyasn1-modules==0.0.5: 0.0.5 from /usr/local/lib/python2.7/dist-packages
        pyasn1>=0.1.4: 0.1.7 from /usr/local/lib/python2.7/dist-packages
      six>=1.6.1: 1.7.3 from /usr/lib/python2.7/dist-packages
      pyasn1==0.1.7: 0.1.7 from /usr/local/lib/python2.7/dist-packages
      rsa==3.1.4: 3.1.4 from /usr/local/lib/python2.7/dist-packages
        pyasn1>=0.1.3: 0.1.7 from /usr/local/lib/python2.7/dist-packages
    requests>=1.1.0,!=1.2.0,!=2.2.1: 2.7.0 from /usr/local/lib/python2.7/dist-packages
    gpsoauth==0.0.3: 0.0.3 from /usr/local/lib/python2.7/dist-packages
      requests: 2.7.0 from /usr/local/lib/python2.7/dist-packages
      pycrypto: 2.6.1 from /usr/local/lib/python2.7/dist-packages
    validictory>=0.8.0,!=0.9.2: 1.0.0 from /usr/local/lib/python2.7/dist-packages
    mutagen>=1.18: 1.29 from /usr/local/lib/python2.7/dist-packages
    proboscis>=1.2.5.1: 1.2.6.0 from /usr/local/lib/python2.7/dist-packages
    mock>=0.7.0: 1.0.1 from /usr/local/lib/python2.7/dist-packages
    python-dateutil>=1.3,!=2.0: 2.4.2 from /usr/local/lib/python2.7/dist-packages
      six>=1.5: 1.7.3 from /usr/lib/python2.7/dist-packages
    protobuf>=2.4.1: 2.6.1 from /usr/local/lib/python2.7/dist-packages
      setuptools: 5.5.1 from /usr/lib/python2.7/dist-packages
    appdirs>=1.1.0: 1.4.0 from /usr/local/lib/python2.7/dist-packages
Mopidy-Scrobbler: 1.1.1 from /usr/share/mopidy
  Mopidy>=0.18: 1.0.5 from /usr/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
    tornado>=2.3: 3.2 from /usr/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
  pylast>=0.5.7: 0.5.11 from /usr/lib/python2.7/dist-packages
Mopidy-Spotify: 1.4.0 from /usr/share/mopidy
  Mopidy>=1.0: 1.0.5 from /usr/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
    tornado>=2.3: 3.2 from /usr/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
  pyspotify>=1.9,<1.999: 1.11 from /usr/lib/pymodules/python2.7
GStreamer: 0.10.36.0 from /usr/lib/python2.7/dist-packages/gst-0.10/gst
  Detailed information: 
    Python wrapper: gst-python 0.10.22.0
    Relevant elements:
      Found:
        uridecodebin
        souphttpsrc
        appsrc
        alsasink
        osssink
        oss4sink
        pulsesink
        id3demux
        id3v2mux
        lame
        mad
        mp3parse
        vorbisdec
        vorbisenc
        vorbisparse
        oggdemux
        oggmux
        oggparse
        flacdec
        flacparse
        shout2send
      Not found:
        flump3dec




Looks like:   pylast>=0.5.7: 0.5.11 from /usr/lib/python2.7/dist-packages

**Comment by jodal** [comment]
Can you reproduce the crash? If so, which track should I play to do so? If
not, then I believe this might be last.fm's fault.

I see that you have pylast 0.5.11, which is the one packaged in Ubuntu
14.10. Security support for 14.10 ends in a couple of weeks, so it is
probably about time to upgrade to Ubuntu 15.04 which comes with pylast
1.0.0. If this is a pylast bug, that might help fix this.

**Comment by hlprimm** [comment]
It would happen on every track. Updating to 15.04 fixed it so maybe it was pylast.

Thanks much.
