### ISSUE TITLE
Scrobbled tracks not saving

### ISSUE THREAD

**Issue by Firestorrrm** [mopidy/mopidy-scrobbler#20]
Whenever a track is playing, it shows on Last.FM, but it doesn't save when it's done playing. Is there any way to fix this?

**Comment by Ciechosz** [comment]
I have the same issue.

**Comment by moon-musick** [comment]
It seems I encountered a similar problem - the track is displayed as 'now playing', but only the last track of a playlist is saved.

I use `mopidy` exclusively with [`mopidy-spotify`](https://github.com/mopidy/mopidy-spotify).

Software versions (everything from APT repository):
* `mopidy 2.0.0-1`
* `mopidy-spotify 3.0.0-0mopidy1`
* `mopidy-scrobbler 1.1.1-3`

**Comment by trygveaa** [comment]
It seems like this is caused by https://github.com/mopidy/mopidy/issues/1456.

We can probably keep this open until that is fixed, and we have confirmed that it fixes this.

**Comment by 0nse** [comment]
@trygveaa is right. @moon-musick, as a temporary fix, you can disable the `time_position` check:
```diff
diff --git mopidy_scrobbler/frontend.py.old mopidy_scrobbler/frontend.py
index 6a34d9e..cd47e82 100644
--- mopidy_scrobbler/frontend.py.old
+++ mopidy_scrobbler/frontend.py
@@ -57,14 +57,9 @@ class ScrobblerFrontend(pykka.ThreadingActor, CoreListener):
         track = tl_track.track
         artists = ', '.join(sorted([a.name for a in track.artists]))
         duration = track.length and track.length // 1000 or 0
-        time_position = time_position // 1000
         if duration < 30:
             logger.debug('Track too short to scrobble. (30s)')
             return
-        if time_position < duration // 2 and time_position < 240:
-            logger.debug(
-                'Track not played long enough to scrobble. (50% or 240s)')
-            return
         if self.last_start_time is None:
             self.last_start_time = int(time.time()) - duration
         logger.debug('Scrobbling track: %s - %s', artists, track.name)
```

**Comment by moon-musick** [comment]
@0nse it works perfectly after I applied the fix, thank you!

**Comment by hubspek** [comment]
that fix leads to fake scrobbles. the track gets scrobbled when you're trying to skip it.

**Comment by jjok** [comment]
@hubspek I think it's just meant as a workaround until the issue with Mopidy is fixed.

**Comment by 0nse** [comment]
@hubspek it's not a fix but a temporary workaround. Look at the provided patch; it scrobbels *everything* disregarding of how long it has been played. If it were a fix, I would have issued a PR.

**Comment by hubspek** [comment]
@jjok It's been called a fix by @0nse from the beginning and that's why I used the term. I know the difference.

And I stated a fact. That, whatever you call it, leads to FAKE scrobbles. That issue has been open for months now. You should keep focus on that rather than educating ppl on insignificant details.

**Comment by jjok** [comment]
@hubspek I'm not sure what you mean. Your options are:

* Use the extension without the patch, which means that nothing scrobbles,
* Use the extension with the patch, which means that everything scrobbles,
* Fix the issue in Mopidy
