### ISSUE TITLE
Cannot receive track_playback_started notification

### ISSUE THREAD

**Issue by LucioSantinelli** [mopidy/mopidy-scrobbler#24]
Hi i wrote a very simple script in Pyton for monitoring mopidy events.

```
import pikka
import time
from moped.core import CoreListener
class EventListener(pukka.ThreadingActor, CoreListener):
        def on_start(self):
              print "Listener started"
        def track_playback_started(self,tl_track):
              print "song_started"

listener=EventListener.start()
```

Im very newbie on python and Mopidy.
What am i missing?

**Comment by kingosticks** [comment]
Hello, can we close this in favour of your discussion at https://discuss.mopidy.com/t/getting-event-from-musicbox-rapesberry-pi/1612/1 (which is where usage questions belong)?
