### ISSUE TITLE
Not working for some reason.

### ISSUE THREAD

**Issue by EinoHR** [mopidy/mopidy-scrobbler#38]
This is my config section for the scrobbler 
```
[scrobbler]
enabled = true
username = FireInsight
password = ********
```
I am running mopidy as a service with the user set to my normal user ~~because I was too lazy to set up perms for my music folder~~.
The config is in both ~/.config/mopidy/mopidy.conf and /etc/mopidy/mopidy.conf

**Comment by jodal** [comment]
Hi! There's nothing actionable here. Please ask for help either on the forums or the Zulip chat. You'll find links to both on [mopidy.com](https://mopidy.com). If you get help and together figure out that this is actually a bug, please come back here and open an issue with enough details for us to debug and fix it.
