### ISSUE TITLE
Add a comments a text_extension.py

### ISSUE THREAD

**Issue by Bredalis** [mopidy/mopidy-scrobbler#43]

**Comment by kingosticks** [comment]
Why?!

**Comment by kingosticks** [comment]
What lines in this file do you think would benefit in some explanation? This is what I meant when I asked you to be more specific, not opening multiple vague issues for different files. 

I appreciate I am familiar with Mopidy and Mopidy extensions but I cannot see anything worth commenting here. Comments for the sake of it are just extra noise with zero benefit.
