### ISSUE TITLE
Google Music tracks aren't remembered after being scrobbled

### ISSUE THREAD

**Issue by Cysioland** [mopidy/mopidy-scrobbler#6]
I'm using Mopidy 0.19.4 with mopidy-scrobbler nad mopidy-gmusic. When I'm playing music, it shows as „Now playing” on last.fm, but after song ends, it doesn't show up in history.

**Comment by liftarn** [comment]
Any change of a fix for this? It worked earlier and now it's broken.

**Comment by jodal** [comment]
I don't use Mopidy-GMusic myself, so I need someone else to reproduce and confirm this and in the best case, pinpoint what and where the bug is.

**Comment by liftarn** [comment]
I tried with YouTube and there I don't get scrobbles either. I don't even get "Now playing".

**Comment by jodal** [comment]
No response in six weeks or so, closing. Please reopen or file a new issue if you have more details so that I can fix this without being a GMusic user myself.

**Comment by jodal** [comment]
Same issue surfaced on the forum now: https://discuss.mopidy.com/t/musicbox-not-scrobbling-to-last-fm/636

**Comment by liftarn** [comment]
Nothing suspicious in mopidy.log.

2015-04-11 04:58:00,425 - INFO     Start refreshing Google Music library
2015-04-11 04:58:00,972 - INFO     Starting new HTTPS connection (1): www.googleapis.com
2015-04-11 04:58:01,017 - ERROR    Spotify login error: Bad username and/or password
2015-04-11 04:58:01,036 - INFO     Disconnected from Spotify
2015-04-11 04:58:01,611 - INFO     Starting Mopidy frontends: ScrobblerFrontend, MpdFrontend, HttpFrontend
2015-04-11 04:58:01,637 - INFO     MPD server running at [::ffff:0.0.0.0]:6600
2015-04-11 04:58:01,658 - INFO     HTTP server running at [::ffff:0.0.0.0]:6680
2015-04-11 04:58:02,063 - INFO     Scrobbler connected to Last.fm

**Comment by liftarn** [comment]
I get a few:
2015-04-11 05:16:17,151 - ERROR    Resource not found. Debug message: gstsouphttpsrc.c(924): gst_soup_http_src_finished_cb (): /GstPlayBin2:playbin20/GstURIDecodeBin:uridecodebin5/GstSoupHTTPSrc:source:
libsoup status code 1
2015-04-11 05:16:17,382 - WARNING  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

**Comment by kingosticks** [comment]
@liftarn are you able to try with the latest mopidy-gmusic version on github? `pip install -u https://github.com/hechtus/mopidy-gmusic/archive/develop.zip` (or thereabouts).

**Comment by renegat59** [comment]
I have the same issue:
Mopidy 1.0.2
Gmusic 1.0.0 (UNRELEASED)
Scrobbler 1.1.1-2

In last.fm there is "now playing" but it doesn't go to the history. No errors, no nothing..

**Comment by jodal** [comment]
Can you run `mopidy -o loglevels/mopidy_scrobbler=debug`, reproduce the issue, and link to a pastebin with the log output?

**Comment by markjewiss** [comment]
I see the same issue today (I have just started using this setup). @jodal I will recreate for you later and post log output requested here.

**Comment by markjewiss** [comment]
Does this help?

pi@vimes ~ $ mopidy -o loglevels/mopidy_scrobbler=debug
INFO     2015-09-11 15:18:29,695 [2698:MainThread] mopidy.__main__
  Starting Mopidy 1.1.0
INFO     2015-09-11 15:18:29,833 [2698:MainThread] mopidy.config
  Loading config from builtin defaults
INFO     2015-09-11 15:18:29,854 [2698:MainThread] mopidy.config
  Loading config from /home/pi/.config/mopidy/mopidy.conf
INFO     2015-09-11 15:18:29,865 [2698:MainThread] mopidy.config
  Loading config from command line options
INFO     2015-09-11 15:18:30,449 [2698:MainThread] mopidy.__main__
  Enabled extensions: http, stream, m3u, scrobbler, softwaremixer, musicbox_webclient, gmusic
INFO     2015-09-11 15:18:30,451 [2698:MainThread] mopidy.__main__
  Disabled extensions: mpd, local, file
INFO     2015-09-11 15:18:32,378 [2698:MainThread] mopidy.commands
  Starting Mopidy mixer: SoftwareMixer
INFO     2015-09-11 15:18:32,389 [2698:MainThread] mopidy.commands
  Starting Mopidy audio
INFO     2015-09-11 15:18:32,400 [2698:MainThread] mopidy.commands
  Starting Mopidy backends: GMusicBackend, StreamBackend, M3UBackend
INFO     2015-09-11 15:18:32,409 [2698:MainThread] mopidy_gmusic.session
  Mopidy uses Google Music
INFO     2015-09-11 15:18:32,489 [2698:Audio-2] mopidy.audio.actor
  Audio output set to "autoaudiosink"
INFO     2015-09-11 15:18:32,517 [2698:MainThread] mopidy.m3u.playlists
  Loaded 0 M3U playlists from /home/pi/.local/share/mopidy/m3u
INFO     2015-09-11 15:18:34,130 [2698:Thread-6] mopidy_gmusic.actor
  Start refreshing Google Music library
INFO     2015-09-11 15:18:34,142 [2698:MainThread] mopidy.commands
  Starting Mopidy core
INFO     2015-09-11 15:18:34,287 [2698:MainThread] mopidy.commands
  Starting Mopidy frontends: ScrobblerFrontend, HttpFrontend
INFO     2015-09-11 15:18:34,307 [2698:HttpFrontend-11] mopidy.http.actor
  HTTP server running at [10.0.2.13]:6680
INFO     2015-09-11 15:18:35,388 [2698:ScrobblerFrontend-9] mopidy_scrobbler.frontend
  Scrobbler connected to Last.fm
searching all access for foals

** (mopidy:2698): WARNING **: Cannot autolaunch D-Bus without X11 $DISPLAY

** (mopidy:2698): WARNING **: Cannot autolaunch D-Bus without X11 $DISPLAY

** (mopidy:2698): WARNING **: Cannot autolaunch D-Bus without X11 $DISPLAY

** (mopidy:2698): WARNING **: Cannot autolaunch D-Bus without X11 $DISPLAY

** (mopidy:2698): WARNING **: Cannot autolaunch D-Bus without X11 $DISPLAY

** (mopidy:2698): WARNING **: Cannot autolaunch D-Bus without X11 $DISPLAY

** (mopidy:2698): WARNING **: Cannot autolaunch D-Bus without X11 $DISPLAY

** (mopidy:2698): WARNING **: Cannot autolaunch D-Bus without X11 $DISPLAY

** (mopidy:2698): WARNING **: Cannot autolaunch D-Bus without X11 $DISPLAY

** (mopidy:2698): WARNING **: Cannot autolaunch D-Bus without X11 $DISPLAY
DEBUG    2015-09-11 15:20:02,772 [2698:ScrobblerFrontend-9] mopidy_scrobbler.frontend
  Now playing track: Foals - Lonely Hunter
WARNING  2015-09-11 15:20:03,580 [2698:MainThread] mopidy.audio.gst
  Element doesn't implement handling of this stream. Please file a bug.
INFO     2015-09-11 15:22:05,099 [2698:Thread-6] mopidy_gmusic.playlists
  Loaded 28 playlists from Google Music
INFO     2015-09-11 15:22:05,102 [2698:Thread-6] mopidy_gmusic.actor
  Finished refreshing Google Music content in 211s

** (mopidy:2698): WARNING **: Cannot autolaunch D-Bus without X11 $DISPLAY

** (mopidy:2698): WARNING **: Cannot autolaunch D-Bus without X11 $DISPLAY

** (mopidy:2698): WARNING **: Cannot autolaunch D-Bus without X11 $DISPLAY

** (mopidy:2698): WARNING **: Cannot autolaunch D-Bus without X11 $DISPLAY

** (mopidy:2698): WARNING **: Cannot autolaunch D-Bus without X11 $DISPLAY
DEBUG    2015-09-11 15:24:46,975 [2698:ScrobblerFrontend-9] mopidy_scrobbler.frontend
  Now playing track: Foals - A Knife In The Ocean
WARNING  2015-09-11 15:24:47,514 [2698:MainThread] mopidy.audio.gst
  Element doesn't implement handling of this stream. Please file a bug.

**Comment by jodal** [comment]
Fixed in develop branch of mopidy-gmusic. Will be part of upcoming 1.0.0 release.

**Comment by anttiautio** [comment]
I have this problem too.

**Comment by kingosticks** [comment]
@anttiautio this issue is with code from 2014 and was reportedly fixed. Please file a new bug report with all the relevant information.
