### ISSUE TITLE
Additional (non-scrobble related functionality)

### ISSUE THREAD

**Issue by IvanMalison** [mopidy/mopidy-scrobbler#9]
I'd like to add some functionality to mopidy (listen to top top tracks by tag) that is related to last.fm, but not scrobbling tracks. Would it be appropriate to add this functionality here or elsewhere? Feel free to close this issue if this is not the appropriate forum/location for this type of functionality.

**Comment by jodal** [comment]
That would probably fit in a Mopidy extension that implements a Mopidy backend. Mopidy-Scrobbler is a Mopidy frontend, and I'd like to keep it simple, just doing scrobbling.
